## ANALISIS DATASET STEEL INDUSTRY ENERGY CONSUMPTION

### Import Library

In [1]:
import pandas as pd
import prettytable as ptl

### Import Dataset yang sudah di acc

In [2]:
df = pd.read_csv("Steel_industry_data.csv")

### Menampilkan informasi dari dataset

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   date                                  35040 non-null  object
 1   Usage_kWh                             35040 non-null  float64
 2   Lagging_Current_Reactive.Power_kVarh  35040 non-null  float64
 3   Leading_Current_Reactive_Power_kVarh  35040 non-null  float64
 4   CO2(tCO2)                             35040 non-null  float64
 5   Lagging_Current_Power_Factor          35040 non-null  float64
 6   Leading_Current_Power_Factor          35040 non-null  float64
 7   NSM                                   35040 non-null  int64
 8   WeekStatus                            35040 non-null  object
 9   Day_of_week                           35040 non-null  object
 10  Load_Type                             35040 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 2.9+ MB

### Menampilkan statistik dari dataset yang bertipe Numerik

In [4]:
df.describe()

,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM
count,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000
mean,27.386892,13.035384,3.870949,0.011524,80.578056,84.367870,42750.000000
std,33.444380,16.306000,7.424463,0.016151,18.921322,30.456535,24940.534317
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.200000,2.300000,0.000000,0.000000,63.320000,99.700000,21375.000000
50%,4.570000,5.000000,0.000000,0.000000,87.960000,100.000000,42750.000000
75%,51.237500,22.640000,2.090000,0.020000,99.022500,100.000000,64125.000000
max,157.180000,96.910000,27.760000,0.070000,100.000000,100.000000,85500.000000

### Menampilkan 10 record pertama dari dataset dengan attribute bertipe angka.

In [5]:
df.select_dtypes(include=['int64','float64']).head(10)

,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM
0,3.17,2.95,0.0,0.0,73.21,100.0,900
1,4.00,4.46,0.0,0.0,66.77,100.0,1800
2,3.24,3.28,0.0,0.0,70.28,100.0,2700
3,3.31,3.56,0.0,0.0,68.09,100.0,3600
4,3.82,4.50,0.0,0.0,64.72,100.0,4500
5,3.28,3.56,0.0,0.0,67.76,100.0,5400
6,3.60,4.14,0.0,0.0,65.62,100.0,6300
7,3.60,4.28,0.0,0.0,64.37,100.0,7200
8,3.28,3.64,0.0,0.0,66.94,100.0,8100
9,3.78,4.72,0.0,0.0,62.51,100.0,9000

### Menampilkan informasi jumlah record, jumlah attribute, nama attribute, jumlah attribute dengan tipe angka, dan dimasukkan kedalam Dictionary.

In [6]:
datasetDictionary = {
    'Jumlah Record': df.shape[0],
    'Jumlah Attribute': df.shape[1],
    'Nama Attribute': df.columns.tolist(),
    'Jumlah Attribute Dengan Tipe Angka': df.select_dtypes(include=['int64', 'float64']).shape[1],
}

table = ptl.PrettyTable()
table.add_column('Jumlah Record', [datasetDictionary['Jumlah Record']])
table.add_column('Jumlah Attribute', [datasetDictionary['Jumlah Attribute']])
table.add_column('Nama Attribute', ['\n'.join(datasetDictionary['Nama Attribute'])])
table.add_column('Jumlah Attribute Dengan Tipe Angka', [datasetDictionary['Jumlah Attribute Dengan Tipe Angka']])
print(table)

+---------------+------------------+--------------------------------------+------------------------------------+
| Jumlah Record | Jumlah Attribute |            Nama Attribute            | Jumlah Attribute Dengan Tipe Angka |
+---------------+------------------+--------------------------------------+------------------------------------+
|     35040     |        11        |                 date                 |                 7                  |
|               |                  |              Usage_kWh               |                                    |
|               |                  | Lagging_Current_Reactive.Power_kVarh |                                    |
|               |                  | Leading_Current_Reactive_Power_kVarh |                                    |
|               |                  |              CO2(tCO2)               |                                    |
|               |                  |     Lagging_Current_Power_Factor     |                                    |
|               |                  |     Leading_Current_Power_Factor     |                                    |
|               |                  |                 NSM                  |                                    |
|               |                  |              WeekStatus              |                                    |
|               |                  |             Day_of_week              |                                    |
|               |                  |              Load_Type               |                                    |
+---------------+------------------+--------------------------------------+------------------------------------+

### Menampilkan nilai dataset pada baris dimulai dengan 3 digit NIM akhir hingga data terakhir dan kolom ke 4 hingga kolom terakhir menggunakan ke 2 metode slice yaitu (iloc dan loc)

In [7]:
df.iloc[24:, 3:]

,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
24,0.00,0.0,67.72,100.00,22500,Weekday,Monday,Light_Load
25,0.00,0.0,69.52,100.00,23400,Weekday,Monday,Light_Load
26,0.00,0.0,65.73,100.00,24300,Weekday,Monday,Light_Load
27,0.00,0.0,68.40,100.00,25200,Weekday,Monday,Light_Load
28,0.00,0.0,68.48,100.00,26100,Weekday,Monday,Light_Load
...,...,...,...,...,...,...,...,...
35035,0.00,0.0,62.10,100.00,82800,Weekday,Monday,Light_Load
35036,0.00,0.0,70.71,100.00,83700,Weekday,Monday,Light_Load
35037,0.07,0.0,76.62,99.98,84600,Weekday,Monday,Light_Load
35038,0.11,0.0,77.72,99.96,85500,Weekday,Monday,Light_Load
35039,0.07,0.0,77.22,99.98,0,Weekday,Monday,Light_Load

In [8]:
df.loc[24:, datasetDictionary['Nama Attribute'][3:]]

,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
24,0.00,0.0,67.72,100.00,22500,Weekday,Monday,Light_Load
25,0.00,0.0,69.52,100.00,23400,Weekday,Monday,Light_Load
26,0.00,0.0,65.73,100.00,24300,Weekday,Monday,Light_Load
27,0.00,0.0,68.40,100.00,25200,Weekday,Monday,Light_Load
28,0.00,0.0,68.48,100.00,26100,Weekday,Monday,Light_Load
...,...,...,...,...,...,...,...,...
35035,0.00,0.0,62.10,100.00,82800,Weekday,Monday,Light_Load
35036,0.00,0.0,70.71,100.00,83700,Weekday,Monday,Light_Load
35037,0.07,0.0,76.62,99.98,84600,Weekday,Monday,Light_Load
35038,0.11,0.0,77.72,99.96,85500,Weekday,Monday,Light_Load
35039,0.07,0.0,77.22,99.98,0,Weekday,Monday,Light_Load

### Menampilkan jumlah label dari semua attribute yang bernilai object

In [9]:
objectList = df.select_dtypes(include=['object']).columns.tolist()
objectList.pop(0)

for i in objectList:
    print(df[i].value_counts())

Weekday    25056
Weekend     9984
Name: WeekStatus, dtype: int64
Monday       5088
Tuesday      4992
Wednesday    4992
Thursday     4992
Friday       4992
Saturday     4992
Sunday       4992
Name: Day_of_week, dtype: int64
Light_Load      18072
Medium_Load      9696
Maximum_Load     7272
Name: Load_Type, dtype: int64